# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcb0c07209976353c3f8eedb4f88b8226cf93522413820d93c405890cbdd5abecbbc602c281e6e56a98664e8fb754821d6a1c24529d20a2a68ab98cdc678b864

test:
  secret_key_base: fcd02b3ab6e3ec4b7e6dbdbbb6ca46f975baa13d93a2f730d0eec7bd983e0fcde64be8698e034d039b712245163d796cfa893b20cf98ec3be728a880ab9c4cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
